title: Guangliang Yang  @  Fudan University
description: >- 
   The home page of Guangliang Yang

nav:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Teaching
    url: /teaching/
  - title: Service
    url: /service/
  - title: Students
    url: /students/
